# Este archivo .http permite hacer peticiones HTTP a la API
GET http://localhost:5075/games

### 

GET http://localhost:5075/games/6

### 

POST http://localhost:5075/games
Content-Type: application/json

{
    "name": "Dying Light",
    "genreId": 2,
    "price": 21.99,
    "releaseDate": "2015-01-27"
}

###

PUT http://localhost:5075/games/1
Content-Type: application/json

{
    "name": "Call of Duty II",
    "genre": "FPS/Shooter",
    "price": 32.99,
    "releaseDate": "2000-02-25"
}

### 

DELETE http://localhost:5075/games/5