# Este archivo .http permite hacer peticiones HTTP a la API
GET http://localhost:5075/games

### 

GET http://localhost:5075/games/5

### 

POST http://localhost:5075/games
Content-Type: application/json

{
    "name": "Dying Light",
    "genreId": 2,
    "price": 24.99,
    "releaseDate": "2015-01-27"
}

###

PUT http://localhost:5075/games/1
Content-Type: application/json

{
    "name": "Dying Light II",
    "genreId": 2,
    "price": 39.99,
    "releaseDate": "2022-02-04"
}

### 

DELETE http://localhost:5075/games/1